---
- name: Check list of Node.js apps running.
  command: forever list
  register: forever_list
  changed_when: false

- name: Create folder for logs
  file:
    path: "{{miner.log_folder}}"
    state: directory
    owner: "{{ansible_user_id}}"
    group: "{{ansible_user_id}}"
  become: yes

- name: Prepare command to start
  set_fact:
    start_command: forever start -a -l {{miner.log_folder}}/miner.log.log -o {{miner.log_folder}}/miner.out.log -e {{miner.log_folder}}/miner.err.log {{miner.executable_path}} --host {{domain}} --port {{miner.port}} --key /etc/letsencrypt/live/{{domain}}/privkey.pem --cert /etc/letsencrypt/live/{{domain}}/fullchain.pem --statistics={{miner.statistics}} --miner={{miner.threads}} --wallet-address={{miner.wallet_address}}

- name: Start example miner app.
  command: "{{start_command}}"
  when: forever_list.stdout.find(miner.executable_path) == -1
  become: yes

- name: Start miner at boot
  lineinfile:
    path: /etc/rc.local
    regexp: ^{{start_command}}
    line: "{{start_command}}"
    insertbefore: ^exit 0
  become: yes

